name: Node.js Package

on:
  release:
    types: [created]

env:
  NPM_TOKEN_2: ${{ secrets.NPM_TOKEN_2 }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_2" >> ~/.npmrc
      - run: npm version patch --no-git-tag-version
      - uses: EndBug/add-and-commit@v8.0.2
        with:
          commit: --signoff
          default_author: user_info
          message: 'Updating version'
          pathspec_error_handling: ignore
      - run: npm publish
#      - uses: actions/upload-artifact@v3
#        with:
#          path: ${{ github.workspace }}
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: *
          allow_override: true